version: '3.8'

services:
  nest-app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '8080:${PORT}'
    volumes:
      - my_volume:/app/data
    environment:
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      - postgres
      - redis
    command: ["sh", "-c", "npx prisma migrate deploy && yarn start:prod"]


  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5433:5432'

  redis:
    image: redis:7.2
    ports:
      - '${REDIS_PORT}:6379'
    restart: always

volumes:
  my_volume:
